# Generated by Django 3.2.10 on 2021-12-09 14:55

from django.db import migrations, models
import django_oidc_id_provider.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Connection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.TextField()),
                ("nonce", models.TextField(default="No Nonce Provided")),
                (
                    "expires_on",
                    models.DateTimeField(
                        default=django_oidc_id_provider.models.default_connection_expiration_date
                    ),
                ),
                ("access_token", models.TextField(default="No token provided")),
            ],
            options={
                "swappable": "FC_AS_FS_CONNECTION_MODEL",
            },
        ),
    ]
